language: python
python:
  - "3.5"
before-install:
  - git clone https://github.com/Hack-Boys-2019/crazyflie-lib-python cflib
  
install:
  - pip install -r requirements.txt
  - pip install -e cflib

script:
  - python drone.py -test
